# Generated by Django 4.2.6 on 2023-10-18 13:46

import core.validators.certidao
import core.validators.cpf
import core.validators.extensao_arquivo
import core.validators.nis
import core.validators.tamanho_arquivo
from django.db import migrations, models
import django.db.models.deletion
import gestao_escolar.models.aluno_documentacao


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nome_social', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(max_length=30)),
                ('cor', models.CharField(choices=[('PRETO', 'Preto'), ('PARDO', 'Pardo'), ('BRANCO', 'Branco'), ('INDIGENA', 'Indígena'), ('AMARELO', 'Amarelo')], max_length=8)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('NAO_BINARIO', 'Não-binário')], max_length=11)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('celular1', models.CharField(blank=True, max_length=20, null=True)),
                ('celular2', models.CharField(blank=True, max_length=20, null=True)),
                ('religiao', models.CharField(blank=True, max_length=30, null=True)),
                ('ocupacao', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('SEPARADO', 'Separado'), ('DIVORCIADO', 'Divorciado'), ('VIUVO', 'Viúvo'), ('UNIAO_ESTAVEL', 'União estável')], max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AlunoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, validators=[core.validators.cpf.validate_cpf])),
                ('responsavel_designado', models.BooleanField()),
                ('celular1', models.CharField(max_length=14)),
                ('celular2', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('ANALFABETO', 'Analfabeto'), ('FUNDAMENTAL_IN', 'Ensino Fundamental Incompleto'), ('FUNDAMENTAL_CO', 'Ensino Fundamental Completo'), ('MEDIO_IN', 'Ensino Médio Incompleto'), ('MEDIO_CO', 'Ensino Médio Completo'), ('SUPERIOR_IN', 'Ensino Superior Incompleto'), ('SUPERIOR_CO', 'Ensino Superior Completo'), ('POS_GRADUACAO', 'Pós-Graduação Completa'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=14, null=True)),
                ('filiacao1', models.BooleanField(blank=True, null=True)),
                ('filiacao2', models.BooleanField(blank=True, null=True)),
                ('parentesco', models.CharField(blank=True, choices=[('PROPRIO', 'Próprio(a) aluno(a)'), ('TIO', 'Tio(a)'), ('AVO', 'Avô(ó)'), ('IRMAO', 'Irmão(ã)'), ('PADRASTO', 'Padrato ou madrasta'), ('OUTRO', 'Outro')], max_length=14, null=True)),
                ('aluno', models.ManyToManyField(related_name='responsaveis', to='gestao_escolar.aluno')),
            ],
            options={
                'verbose_name': 'Pai/Responsável de aluno',
                'verbose_name_plural': 'Pais/Reponsáveis de alunos',
                'db_table': 'aluno_responsavel',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AlunoEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('municipio', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=20)),
                ('zona_residencial', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10)),
                ('complemento', models.TextField(blank=True, max_length=100, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='gestao_escolar.aluno')),
            ],
            options={
                'verbose_name': 'Endereço de aluno',
                'verbose_name_plural': 'Endereços de alunos',
                'db_table': 'aluno_endereco',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AlunoDocumentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to=gestao_escolar.models.aluno_documentacao.diretorio_de_arquivos_do_aluno, validators=[core.validators.extensao_arquivo.validate_extensao_imagem, core.validators.tamanho_arquivo.validate_tamanho_arquivo])),
                ('comprovante_endereco', models.FileField(blank=True, null=True, upload_to=gestao_escolar.models.aluno_documentacao.diretorio_de_arquivos_do_aluno, validators=[core.validators.extensao_arquivo.validate_extensao_arquivo, core.validators.tamanho_arquivo.validate_tamanho_arquivo])),
                ('rg', models.CharField(blank=True, max_length=9, null=True)),
                ('rne', models.CharField(blank=True, max_length=9, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=8, null=True)),
                ('data_expedicao', models.DateField(blank=True, null=True)),
                ('data_entrada_no_pais', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[core.validators.cpf.validate_cpf])),
                ('nis', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[core.validators.nis.validate_nis])),
                ('registro_alistamento', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('cartao_sus', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('id_educacenso', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('certidao_nova', models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[core.validators.certidao.validate_certidao])),
                ('cert_antiga_livro', models.CharField(blank=True, max_length=6)),
                ('cert_antiga_folha', models.CharField(blank=True, max_length=3)),
                ('cert_antiga_termo', models.CharField(blank=True, max_length=7)),
                ('tipo_certidao', models.CharField(blank=True, choices=[('NASCIMENTO', 'Nascimento'), ('CASAMENTO', 'Casamento')], max_length=10, null=True)),
                ('passaporte', models.CharField(blank=True, max_length=8, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacao', to='gestao_escolar.aluno')),
            ],
            options={
                'verbose_name': 'Documentação de aluno',
                'verbose_name_plural': 'Documentações de alunos',
                'db_table': 'aluno_documentacao',
                'ordering': ['-id'],
            },
        ),
    ]
